name: touchnotebookbeta_flutter
description: "Touch NoteBook"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  intl: ^0.20.2
  animations: ^2.0.11
  mask_text_input_formatter: ^2.4.0
  overlay_support: ^2.1.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  flutter_timezone: ^3.0.0
  shared_preferences: ^2.2.3
  webview_flutter: ^4.7.0
  share_plus: ^10.1.2
  package_info_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/policies/privacy_policy.html
    - assets/policies/user_agreement.html


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png