name: touchnotebookbeta_flutter
description: "Touch NoteBook"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  intl: ^0.20.2
  mask_text_input_formatter: ^2.4.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  # Enables generation of localization files
  generate: true
  assets:
    - assets/

